apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.178:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpRMk5qTXpPREl3SGhjTk1qVXhNakF5TURneE5qSXlXaGNOTXpVeE1UTXdNRGd4TmpJeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpRMk5qTXpPREl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFROXVLV240QlF3VmtqY1JLbTVqazhCaFlFOWtmQjMwb0ZrTzc0V0dUbFQKZW8vZGgrQ0JiTXVOVkhaalBpek1LeXVLZll0Y1FXSHpBeHBDUTBEMGZKUjRvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXBScWorQWgyMDMrcFRhRDFOc29KCmRnd1J5Wjh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnT1BDWERXY2dPcEpTdFNHREpwTDNMRC9xZ2tpaFpTWkEKSGxoVmJOSmt3Q2dDSVFDeVA1S3hwTW5pRnR3TUxlY0xiNkh1TytPZy83UE9RYzZZbDNUeldHWVN0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: vibecode
  context:
    cluster: local
    namespace: vibecode
    user: vibecode-sa
current-context: vibecode
users:
- name: vibecode-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImU0bVdQV2tVSWVaWWFaRXpQZmJUdnd0WUt2eWpKOHF3OWlEQWI2SnAxQkkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ2aWJlY29kZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ2aWJlY29kZS1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ2aWJlY29kZS1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZhZTRhMzdmLWZiOWItNDIzNi1iYTcyLTk1ZjgwMTdmYWYxZSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp2aWJlY29kZTp2aWJlY29kZS1zYSJ9.IijGJ0CzoPNMSVtWMYAjIV6UxzOM_OOsiFQOqDj5TNso6SrWMQt3N8SBPXpmLF1TvK6XLAX37X57Z8BXZcGG0ySXH5YeAr1xZiJuZ-OsaIKJubiIrHdlBa7GDifucxDXC8yMU1j6eAgkk5loSF_vlj85ee6Vw2Js8vY3-qCSdrcPXK9S82HeumD5bbx9NlqIxGwD_vbcV1BRdPlm8RiKAAWrYvtPtlZl5W6rAhmQDMahBAEYy4euieI5HnKVpqRF4ktxI3CF1-QS_G4m3-Nd0ptMh1jYfudBIjrmbX5Rj3ZqqrUnBurmmEq8lg-1h6RhVgghWBHoEnpm0IUJEEobGg
